-- MIGRATION: tambah Data Gaji per Karyawan + Absensi Bulanan + payroll harian.
-- Pakai file ini kalau database lama mau dipertahankan tanpa reset.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.data_gaji (
  id bigint generated by default as identity primary key,
  karyawan_id bigint not null unique references public.karyawan(id) on delete cascade,
  gaji_pokok numeric(15,2) not null default 0,
  uang_makan_harian numeric(15,2) not null default 0,
  transport_harian numeric(15,2) not null default 0,
  tunjangan_harian numeric(15,2) not null default 0,
  bpjs_kesehatan_default numeric(15,2) not null default 0,
  bpjs_ketenagakerjaan_default numeric(15,2) not null default 0,
  potongan_lain_default numeric(15,2) not null default 0,
  is_active boolean not null default true,
  catatan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_data_gaji_updated_at on public.data_gaji;
create trigger trg_data_gaji_updated_at before update on public.data_gaji for each row execute function public.set_updated_at();

create table if not exists public.absensi_bulanan (
  id bigint generated by default as identity primary key,
  karyawan_id bigint not null references public.karyawan(id) on delete cascade,
  bulan int not null check (bulan between 1 and 12),
  tahun int not null check (tahun >= 2020),
  total_hadir int not null default 0,
  total_izin int not null default 0,
  total_sakit int not null default 0,
  total_alpha int not null default 0,
  total_cuti int not null default 0,
  keterangan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(karyawan_id, bulan, tahun)
);

drop trigger if exists trg_absensi_bulanan_updated_at on public.absensi_bulanan;
create trigger trg_absensi_bulanan_updated_at before update on public.absensi_bulanan for each row execute function public.set_updated_at();

alter table public.gaji add column if not exists total_hadir int not null default 0;
alter table public.gaji add column if not exists total_izin int not null default 0;
alter table public.gaji add column if not exists total_sakit int not null default 0;
alter table public.gaji add column if not exists total_alpha int not null default 0;
alter table public.gaji add column if not exists total_cuti int not null default 0;
alter table public.gaji add column if not exists tarif_uang_makan_harian numeric(15,2) not null default 0;
alter table public.gaji add column if not exists tarif_transport_harian numeric(15,2) not null default 0;
alter table public.gaji add column if not exists tarif_lain_harian numeric(15,2) not null default 0;
alter table public.gaji add column if not exists uang_lain_harian numeric(15,2) not null default 0;

-- Buat struktur gaji awal untuk semua karyawan aktif berdasarkan jabatan.
insert into public.data_gaji (karyawan_id, gaji_pokok, uang_makan_harian, transport_harian, tunjangan_harian, bpjs_kesehatan_default, bpjs_ketenagakerjaan_default, potongan_lain_default, is_active, catatan)
select
  k.id,
  coalesce(j.gaji_pokok_default, 0),
  25000,
  15000,
  5000,
  0,
  0,
  0,
  true,
  'Dibuat otomatis dari migration payroll.'
from public.karyawan k
left join public.jabatan j on j.id = k.jabatan_id
on conflict (karyawan_id) do nothing;

-- Buat rekap absensi bulan berjalan dari absensi harian yang sudah ada.
insert into public.absensi_bulanan (karyawan_id, bulan, tahun, total_hadir, total_izin, total_sakit, total_alpha, total_cuti, keterangan)
select
  k.id,
  extract(month from now())::int,
  extract(year from now())::int,
  coalesce(sum(case when a.status = 'hadir' then 1 else 0 end), 0)::int,
  coalesce(sum(case when a.status = 'izin' then 1 else 0 end), 0)::int,
  coalesce(sum(case when a.status = 'sakit' then 1 else 0 end), 0)::int,
  coalesce(sum(case when a.status = 'alpha' then 1 else 0 end), 0)::int,
  coalesce(sum(case when a.status = 'cuti' then 1 else 0 end), 0)::int,
  'Rekap awal otomatis dari data absensi harian.'
from public.karyawan k
left join public.absensi a on a.karyawan_id = k.id
  and date_part('month', a.tanggal) = date_part('month', now())
  and date_part('year', a.tanggal) = date_part('year', now())
group by k.id
on conflict (karyawan_id, bulan, tahun) do nothing;

select 'OK_PAYROLL_STRUCTURE_READY' as status,
  (select count(*) from public.data_gaji) as data_gaji,
  (select count(*) from public.absensi_bulanan) as absensi_bulanan;
